import { 
  APP_NAME as SHARED_APP_NAME,
  APP_DESCRIPTION as SHARED_APP_DESCRIPTION,
  SUPPORT_EMAIL as SHARED_SUPPORT_EMAIL,
  LEGAL_EMAIL,
  PRIVACY_EMAIL,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MAX_COMPARE_ITEMS,
  MIN_BOOKING_MONTHS,
  MAX_BOOKING_MONTHS,
  MIN_REVIEW_LENGTH,
  MAX_REVIEW_LENGTH,
  MAX_IMAGE_SIZE_MB,
  ACCEPTED_IMAGE_TYPES,
  MAX_IMAGES_PER_HOSTEL,
  AUTH_RATE_LIMIT,
  API_RATE_LIMIT,
  HOSTEL_REVALIDATE,
  SEARCH_REVALIDATE,
  HOME_REVALIDATE
} from "@hostello/shared";

export const APP_NAME = SHARED_APP_NAME;
export const APP_DESCRIPTION = SHARED_APP_DESCRIPTION;

// Support channels with env overrides
export const SUPPORT_EMAIL = process.env.SUPPORT_EMAIL ?? SHARED_SUPPORT_EMAIL;

export {
  LEGAL_EMAIL,
  PRIVACY_EMAIL,
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  MAX_COMPARE_ITEMS,
  MIN_BOOKING_MONTHS,
  MAX_BOOKING_MONTHS,
  MIN_REVIEW_LENGTH,
  MAX_REVIEW_LENGTH,
  MAX_IMAGE_SIZE_MB,
  ACCEPTED_IMAGE_TYPES,
  MAX_IMAGES_PER_HOSTEL,
  AUTH_RATE_LIMIT,
  API_RATE_LIMIT,
  HOSTEL_REVALIDATE,
  SEARCH_REVALIDATE,
  HOME_REVALIDATE
};
